package com.ubad.academy.di

import com.ubad.academy.BuildConfig
import com.ubad.academy.core.cloud.CloudConfig
import dagger.Module
import dagger.Provides
import dagger.hilt.InstallIn
import dagger.hilt.components.SingletonComponent
import okhttp3.OkHttpClient
import java.util.concurrent.TimeUnit
import javax.inject.Qualifier
import javax.inject.Singleton

/** OkHttp client tuned for large uploads/downloads (course PDFs and video). */
@Qualifier @Retention(AnnotationRetention.BINARY) annotation class CloudUpload

@Module
@InstallIn(SingletonComponent::class)
object CloudModule {

    /**
     * The public cloud client configuration, taken from `BuildConfig`.
     *
     * These values are generated by `app/build.gradle.kts` from Gradle
     * properties / environment variables and are public by design — see
     * [CloudConfig]. Nothing secret is read or shipped here.
     */
    @Provides @Singleton
    fun cloudConfig(): CloudConfig = CloudConfig(
        projectId = BuildConfig.FIREBASE_PROJECT_ID,
        webApiKey = BuildConfig.FIREBASE_WEB_API_KEY,
        appId = BuildConfig.FIREBASE_APP_ID,
        senderId = BuildConfig.FIREBASE_SENDER_ID,
        storageBucket = BuildConfig.FIREBASE_STORAGE_BUCKET,
        authDomain = BuildConfig.FIREBASE_AUTH_DOMAIN,
        workerUrl = BuildConfig.CLOUD_WORKER_URL,
        googleWebClientId = BuildConfig.GOOGLE_WEB_CLIENT_ID,
    )

    /**
     * The web app allows a 120 s upload window (`storage-backend` notes it
     * explicitly); the shared 30 s client would abort big course files on a slow
     * connection.
     */
    @Provides @Singleton @CloudUpload
    fun cloudOkHttp(): OkHttpClient = OkHttpClient.Builder()
        .connectTimeout(20, TimeUnit.SECONDS)
        .readTimeout(120, TimeUnit.SECONDS)
        .writeTimeout(120, TimeUnit.SECONDS)
        .callTimeout(180, TimeUnit.SECONDS)
        .retryOnConnectionFailure(true)
        .build()
}
